version: '3.9'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=studentmanagement
      - POSTGRES_USER=studentmanagement
      - POSTGRES_PASSWORD=askthestudent!
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: